name: ci 

on: push

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
             - name: Checkout repo
               uses: actions/checkout@v3
             - name: Install dependencies
               run: npm install
             - name: Run test
               run: npm test
             - name: Run Cypress tests for Swagger UI
               run: npm run cypress:run 
               env: 
                   BASE_URL: https://softwareengineering2projects.onrender.com/docs/
             
             
        
        
